package se.sveaekonomi.webpay.integration.util.constant;


public enum PAYMENTMETHOD {
    
    BANKAXESS(PAYMENTMETHODTYPE.DIRECT),
    DBAKTIAFI(PAYMENTMETHODTYPE.DIRECT),
    DBALANDSBANKENFI(PAYMENTMETHODTYPE.DIRECT),
    DBDANSKEBANKSE(PAYMENTMETHODTYPE.DIRECT),
    DBNORDEAEE(PAYMENTMETHODTYPE.DIRECT),
    DBNORDEAFI(PAYMENTMETHODTYPE.DIRECT),
    DBNORDEASE(PAYMENTMETHODTYPE.DIRECT),
    DBPOHJOLAFI(PAYMENTMETHODTYPE.DIRECT),
    DBSAMPOFI(PAYMENTMETHODTYPE.DIRECT),
    DBSEBSE(PAYMENTMETHODTYPE.DIRECT),
    DBSEBFTGSE(PAYMENTMETHODTYPE.DIRECT),
    DBSHBFI(PAYMENTMETHODTYPE.DIRECT),
    DBSHBSE(PAYMENTMETHODTYPE.DIRECT),
    DBSPANKKIFI(PAYMENTMETHODTYPE.DIRECT),
    DBSWEDBANKSE(PAYMENTMETHODTYPE.DIRECT),
    DBTAPIOLAFI(PAYMENTMETHODTYPE.DIRECT),
    KORTCERT(PAYMENTMETHODTYPE.CARD),
    SKRILL(PAYMENTMETHODTYPE.CARD),
    //KORTSKRILL(PAYMENTMETHODTYPE.CARD),
    KORTWN(PAYMENTMETHODTYPE.CARD),
    MICRODEB(PAYMENTMETHODTYPE.PREPAID),
    PAYGROUND(PAYMENTMETHODTYPE.PSP),
    PAYPAL(PAYMENTMETHODTYPE.PSP),    
    SVEAINVOICESE(PAYMENTMETHODTYPE.INVOICE),
    SVEASPLITSE(PAYMENTMETHODTYPE.INVOICE),
    SVEAINVOICEEU_SE(PAYMENTMETHODTYPE.INVOICE),
    SVEAINVOICEEU_NO(PAYMENTMETHODTYPE.INVOICE),
    SVEAINVOICEEU_DK(PAYMENTMETHODTYPE.INVOICE),
    SVEAINVOICEEU_FI(PAYMENTMETHODTYPE.INVOICE),
    SVEAINVOICEEU_NL(PAYMENTMETHODTYPE.INVOICE),
    SVEAINVOICEEU_DE(PAYMENTMETHODTYPE.INVOICE),
    SVEASPLITEU_SE(PAYMENTMETHODTYPE.INVOICE),
    SVEASPLITEU_NO(PAYMENTMETHODTYPE.INVOICE),
    SVEASPLITEU_DK(PAYMENTMETHODTYPE.INVOICE),
    SVEASPLITEU_FI(PAYMENTMETHODTYPE.INVOICE),
    SVEASPLITEU_DE(PAYMENTMETHODTYPE.INVOICE),
    SVEASPLITEU_NL(PAYMENTMETHODTYPE.INVOICE);
    
    private PAYMENTMETHODTYPE type;
    
    PAYMENTMETHOD(PAYMENTMETHODTYPE type) {
        this.type = type;
    }
    
    public boolean isDirectPayment() {
        if (PAYMENTMETHODTYPE.DIRECT.equals(type)) {
            return true;
        }
        else {
            return false;
        }
    }
    
    public boolean isCardPayment() {
        if (PAYMENTMETHODTYPE.CARD.equals(type)) {
            return true;
        }
        else {
            return false;
        }
    }
    
    public boolean isInvoicePayment() {
        if (PAYMENTMETHODTYPE.INVOICE.equals(type)) {
            return true;
        }
        else {
            return false;
        }
    }
    
    public PAYMENTMETHODTYPE getType() {
        return type;
    }
}
