package se.sveaekonomi.webpay.integration.util.constant;


public enum PAYMENTMETHOD {
    //--DIRECT BANK--
    BANKAXESS(PAYMENTMETHODTYPE.DIRECT, "BANKAXESS"), //new - not yet implemented in code
    //AKTIA_FI(PAYMENTMETHODTYPE.DIRECT, "DBAKTIAFI"),
    //ALANDSBANKEN_FI(PAYMENTMETHODTYPE.DIRECT, "DBALANDSBANKENFI"),
    //DANSKEBANK_SE(PAYMENTMETHODTYPE.DIRECT, "DBDANSKEBANKSE"),
    //NORDEA_EE(PAYMENTMETHODTYPE.DIRECT, "DBNORDEAEE"),
    //NORDEA_FI(PAYMENTMETHODTYPE.DIRECT, "DBNORDEAFI"),
    NORDEA_SE(PAYMENTMETHODTYPE.DIRECT, "DBNORDEASE"),
    //POHJOLA_FI(PAYMENTMETHODTYPE.DIRECT, "DBPOHJOLAFI"),
    //SAMPOFI(PAYMENTMETHODTYPE.DIRECT, "DBSAMPOFI"),
    SEB_SE(PAYMENTMETHODTYPE.DIRECT, "DBSEBSE"),
    SEBFTG_SE(PAYMENTMETHODTYPE.DIRECT, "DBSEBFTGSE"),
    //DBSHBFI(PAYMENTMETHODTYPE.DIRECT, "DBSHBFI"),
    SHB_SE(PAYMENTMETHODTYPE.DIRECT, "DBSHBSE"),
    //SHB_FI(PAYMENTMETHODTYPE.DIRECT, "DBSPANKKIFI"),
    //SPANKKI_FI(PAYMENTMETHODTYPE.DIRECT, "DBSPANKKIFI"),
    SWEDBANK_SE(PAYMENTMETHODTYPE.DIRECT, "DBSWEDBANKSE"),
    //TAPIOLA_FI(PAYMENTMETHODTYPE.DIRECT, "DBTAPIOLAFI"),
    
    //--CARD--
    KORTCERT(PAYMENTMETHODTYPE.CARD, "KORTCERT"),
    SKRILL(PAYMENTMETHODTYPE.CARD, "SKRILL"),    
    //KORTSKRILL(PAYMENTMETHODTYPE.CARD, "KORTSKRILL"),
    //KORTWN(PAYMENTMETHODTYPE.CARD, KORTWN),
    
    //--PREPAID--
    //MICRODEB(PAYMENTMETHODTYPE.PREPAID, "MICRODEB"),
    
    //--PSP-- 
    //PAYGROUND(PAYMENTMETHODTYPE.PSP, "PAYGROUND"),
    PAYPAL(PAYMENTMETHODTYPE.PSP, "PAYPAL"),
    
    //--INVOICE--
    INVOICE(PAYMENTMETHODTYPE.INVOICE, "INVOICE"),
    /*SVEAINVOICESE(PAYMENTMETHODTYPE.INVOICE, "SVEAINVOICESE"),
    SVEASPLITSE(PAYMENTMETHODTYPE.INVOICE, "SVEASPLITSE"),
    SVEAINVOICEEU_SE(PAYMENTMETHODTYPE.INVOICE, "SVEAINVOICEEU_SE"),
    SVEAINVOICEEU_NO(PAYMENTMETHODTYPE.INVOICE, "SVEAINVOICEEU_NO"),
    SVEAINVOICEEU_DK(PAYMENTMETHODTYPE.INVOICE, "SVEAINVOICEEU_DK"),
    SVEAINVOICEEU_FI(PAYMENTMETHODTYPE.INVOICE, "SVEAINVOICEEU_FI"),
    SVEAINVOICEEU_NL(PAYMENTMETHODTYPE.INVOICE, "SVEAINVOICEEU_NL"),
    SVEAINVOICEEU_DE(PAYMENTMETHODTYPE.INVOICE, "SVEAINVOICEEU_DE"),*/
    
    //--PAYMENT PLAN--
    PAYMENTPLAN(PAYMENTMETHODTYPE.PAYMENTPLAN, "PAYMENTPLAN");       
    //--PAYMENTPLAN
    /*SVEASPLITEU_SE(PAYMENTMETHODTYPE.PAYMENTPLAN, "SVEASPLITEU_SE"),
    SVEASPLITEU_NO(PAYMENTMETHODTYPE.PAYMENTPLAN, "SVEASPLITEU_NO"),
    SVEASPLITEU_DK(PAYMENTMETHODTYPE.PAYMENTPLAN, "SVEASPLITEU_DK"),
    SVEASPLITEU_FI(PAYMENTMETHODTYPE.PAYMENTPLAN, "SVEASPLITEU_FI"),
    SVEASPLITEU_DE(PAYMENTMETHODTYPE.PAYMENTPLAN, "SVEASPLITEU_DE"),
    SVEASPLITEU_NL(PAYMENTMETHODTYPE.PAYMENTPLAN, "SVEASPLITEU_NL");
   */ 
    private PAYMENTMETHODTYPE type;
    private String value;
    
    PAYMENTMETHOD(PAYMENTMETHODTYPE type, String value) {
        this.type = type;
        this.value = value;
    }
    
    public String getValue() {
    	return this.value;
    }
    
    public boolean isDirectPayment() {
        if (PAYMENTMETHODTYPE.DIRECT.equals(type)) {
            return true;
        }
        else {
            return false;
        }
    }
    
    public boolean isCardPayment() {
        if (PAYMENTMETHODTYPE.CARD.equals(type)) {
            return true;
        }
        else {
            return false;
        }
    }
    
    public boolean isInvoicePayment() {
        if (PAYMENTMETHODTYPE.INVOICE.equals(type)) {
            return true;
        }
        else {
            return false;
        }
    }
    
    public PAYMENTMETHODTYPE getType() {
        return type;
    }
}
