package se.sveaekonomi.webpay.integration.hosted.hostedadmin;

import java.io.ByteArrayOutputStream;
import java.io.UnsupportedEncodingException;

import javax.xml.stream.XMLOutputFactory;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamWriter;

import se.sveaekonomi.webpay.integration.exception.SveaWebPayException;
import se.sveaekonomi.webpay.integration.order.handle.DeliverOrderRowsBuilder;
import se.sveaekonomi.webpay.integration.response.hosted.hostedadmin.AnnulTransactionResponse;
import se.sveaekonomi.webpay.integration.response.hosted.hostedadmin.LowerTransactionResponse;
import se.sveaekonomi.webpay.integration.util.constant.PAYMENTTYPE;

/**
 * lowerTransaction modifies the amount in an existing card transaction 
 * having status AUTHORIZED or CONFIRMED. If the amount is lowered by an 
 * amount equal to the transaction authorized amount, then after a 
 * successful request the transaction will get the status ANNULLED.
 * 
 * @author Kristian Grossman-Madsen
 */
public class LowerTransactionRequest extends HostedAdminRequest<DeliverOrderRowsBuilder> {

    /** Required. */
	public String transactionId;
    /** Required. Use minor currency (i.e. 1 SEK => 100 in minor currency) */
	public Integer amountToLower;
    /** Optional. Iff true, doRequest() will perform a confirm request following a successful loweramount request */
	public Boolean alsoDoConfirm;
	
	public Boolean getAlsoDoConfirm() {
		return alsoDoConfirm;
	}

	public LowerTransactionRequest setAlsoDoConfirm(Boolean alsoDoConfirm) {
		this.alsoDoConfirm = alsoDoConfirm;
		return this;
	}

	public String getTransactionId() {
		return transactionId;
	}

	public LowerTransactionRequest setAmountToLower(Integer amountToLower) {
		this.amountToLower = amountToLower;
		return this;
	}	
	
	public double getAmountToLower() {
		return amountToLower;
	}

	public LowerTransactionRequest setTransactionId(String transactionId) {
		this.transactionId = transactionId;
		return this;
	}

	public LowerTransactionRequest(DeliverOrderRowsBuilder order) {
		super(order, "loweramount");
	}

	public String getRequestMessageXml() {

		XMLOutputFactory xmlof = XMLOutputFactory.newInstance();
		ByteArrayOutputStream os = new ByteArrayOutputStream();

		try {
			XMLStreamWriter xmlw = xmlof.createXMLStreamWriter(os, "UTF-8");

			xmlw.writeStartDocument("UTF-8", "1.0");
				xmlw.writeComment("Message generated by Integration package Java");
				xmlw.writeStartElement("loweramount");
					xmlw.writeStartElement("transactionid");
						xmlw.writeCharacters(this.transactionId);
					xmlw.writeEndElement();
					xmlw.writeStartElement("amounttolower");
						xmlw.writeCharacters(Integer.toString(this.amountToLower));
					xmlw.writeEndElement();
				xmlw.writeEndElement();
			xmlw.writeEndDocument();
			xmlw.close();
		} catch (XMLStreamException e) {
			throw new SveaWebPayException("Error when building XML", e);
		}

		try {
			return new String(os.toByteArray(), "UTF-8");
		} catch (UnsupportedEncodingException e) {
			throw new SveaWebPayException("Unsupported encoding UTF-8", e);
		}
	}

	@SuppressWarnings("unchecked")
	public LowerTransactionResponse parseResponse(String message) {
		return new LowerTransactionResponse(message, this.config.getSecretWord(PAYMENTTYPE.HOSTED, this.order.getCountryCode()));
	}

    public String validateOrder() {
        String errors = "";
        if (this.order.getCountryCode() == null) {
            errors += "MISSING VALUE - CountryCode is required, use setCountryCode(...).\n";
        }
        
        if (this.transactionId == null) {
            errors += "MISSING VALUE - OrderId is required, use setOrderId().\n";
    	}
        return errors;    
    }	
}
