package se.sveaekonomi.webpay.integration.hosted.hostedadmin;

import java.io.ByteArrayOutputStream;
import java.io.UnsupportedEncodingException;
import java.util.Hashtable;

import javax.xml.stream.XMLOutputFactory;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamWriter;

import se.sveaekonomi.webpay.integration.Requestable;
import se.sveaekonomi.webpay.integration.exception.SveaWebPayException;
import se.sveaekonomi.webpay.integration.order.handle.QueryOrderBuilder;
import se.sveaekonomi.webpay.integration.response.hosted.hostedadmin.QueryTransactionResponse;
import se.sveaekonomi.webpay.integration.util.constant.PAYMENTTYPE;

public class QueryTransactionRequest extends HostedAdminRequest<QueryOrderBuilder> implements Requestable {

	public QueryTransactionRequest( QueryOrderBuilder orderbuilder ) {		
		super(orderbuilder, "querytransactionid");	
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public QueryTransactionResponse doRequest() {
		return super.doRequest();
	}	

	/**
	 * validates that all required attributes needed for the request are present in the builder object
	 * @return indicating which methods are missing, or empty String if no problems found
	 */
	public String validateOrder() {
		String errors = "";		
		errors += validateOrderId((QueryOrderBuilder)this.order);
		errors += validateCountryCode((QueryOrderBuilder)this.order);
		return errors;
	}
	
    private String validateOrderId(QueryOrderBuilder order) {
    	return (order.getOrderId() == 0L) ? "MISSING VALUE - setOrderId is required.\n" : "";	// orderId is long, i.e. initialised as 0
    }
   
    private String validateCountryCode(QueryOrderBuilder order) {
        return (order.getCountryCode() == null) ? "MISSING VALUE - CountryCode is required, use setCountryCode(...).\n" : "";
    }	
    

    /**
	 * returns xml for hosted webservice "query" request
	 */
	public String getRequestMessageXml() {

		XMLOutputFactory xmlof = XMLOutputFactory.newInstance();
		ByteArrayOutputStream os = new ByteArrayOutputStream();

		try {
			XMLStreamWriter xmlw = xmlof.createXMLStreamWriter(os, "UTF-8");

			xmlw.writeStartDocument("UTF-8", "1.0");
				xmlw.writeComment("Message generated by Integration package Java");
				xmlw.writeStartElement("querytransactionid");	// TODO change to this.method
					xmlw.writeStartElement("transactionid");
						xmlw.writeCharacters( String.valueOf( ((QueryOrderBuilder)this.order).getOrderId() ) );
					xmlw.writeEndElement();
				xmlw.writeEndElement();
			xmlw.writeEndDocument();
			xmlw.close();
		} catch (XMLStreamException e) {
			throw new SveaWebPayException("Error when building XML", e);
		}

		try {
			return new String(os.toByteArray(), "UTF-8");
		} catch (UnsupportedEncodingException e) {
			throw new SveaWebPayException("Unsupported encoding UTF-8", e);
		}
	}    
    @SuppressWarnings("unchecked")
	public QueryTransactionResponse parseResponse(String message) {
		return new QueryTransactionResponse(message, this.config.getSecretWord(PAYMENTTYPE.HOSTED, this.order.getCountryCode()));
	}    
    
	@Override
	@SuppressWarnings("unchecked")
	public Hashtable<String,String> prepareRequest() {		
		return super.prepareRequest();
	}    
    
}
