package se.sveaekonomi.webpay.integration.webservice.helper;

import org.junit.Before;
import org.junit.Test;

import se.sveaekonomi.webpay.integration.order.create.CreateOrderBuilder;
import se.sveaekonomi.webpay.integration.order.row.Item;
import se.sveaekonomi.webpay.integration.util.constant.COUNTRYCODE;
import se.sveaekonomi.webpay.integration.webservice.svea_soap.SveaCreateOrder;
import se.sveaekonomi.webpay.integration.webservice.svea_soap.SveaRequest;


public class WebServiceXmlBuilderTest {
    
    WebServiceXmlBuilder xmlBuilder;
    CreateOrderBuilder orderBuilder;
    String xml;
    
    @Before
    public void setUp() {
        xmlBuilder = new WebServiceXmlBuilder();
        orderBuilder = new CreateOrderBuilder();
        xml = "";
    }
    
    @Test
    public void testCreateOrderEu() throws Exception {        
        orderBuilder.addCustomerDetails(Item.individualCustomer()
                .setSsn(194609052222L));
        orderBuilder.addOrderRow(Item.orderRow()
                .setAmountExVat(100.00)
                .setQuantity(1)
                .setVatPercent(25));
        SveaRequest<SveaCreateOrder> request = orderBuilder.setCountryCode(COUNTRYCODE.SE)
                .setOrderDate("2012-12-12")
                .setClientOrderNumber("33")
                .setCurrency("SEK")
                .useInvoicePayment()
                //returns an InvoicePayment object
                    .prepareRequest();
        
        
        try {
            xml = xmlBuilder.getCreateOrderEuXml((SveaCreateOrder)request.request);
        } catch (Exception e) {
            throw e;
        }
        
 //       final String EXPECTED_XML = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><!--Message generated by Integration package Java V1.0.1--><CreateOrderEu><request><Auth><ClientNumber>79021</ClientNumber><UserName>sverigetest</UserName><Password>sverigetest</Password></Auth><CreateOrderInformation><OrderRows></OrderRows></CreateOrderInformation></request></CreateOrderEu>";
  //      assertTrue(EXPECTED_XML.equals(xml));
        
    }
    
}

