package se.sveaekonomi.webpay.integration.hosted.helper;

import java.io.ByteArrayOutputStream;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.List;

import javax.xml.stream.XMLOutputFactory;
import javax.xml.stream.XMLStreamException;

import se.sveaekonomi.webpay.integration.exception.SveaWebPayException;
import se.sveaekonomi.webpay.integration.hosted.HostedOrderRowBuilder;
import se.sveaekonomi.webpay.integration.hosted.payment.HostedPayment;
import se.sveaekonomi.webpay.integration.order.create.CreateOrderBuilder;
import se.sveaekonomi.webpay.integration.order.identity.CompanyCustomer;
import se.sveaekonomi.webpay.integration.order.identity.CustomerIdentity;
import se.sveaekonomi.webpay.integration.order.identity.IndividualCustomer;
import se.sveaekonomi.webpay.integration.util.xml.XMLBuilder;

public class HostedXmlBuilder extends XMLBuilder {
    
    public String getXml(HostedPayment<?> payment) throws Exception {
        XMLOutputFactory xmlof = XMLOutputFactory.newInstance();
        ByteArrayOutputStream os = new ByteArrayOutputStream();
        CreateOrderBuilder order = payment.getCreateOrderBuilder();
        ArrayList<HostedOrderRowBuilder> rows = payment.getRowBuilder();
        
        xmlw = xmlof.createXMLStreamWriter(os, "UTF-8");
        xmlw.writeStartDocument("UTF-8", "1.0");
        xmlw.writeComment("Message generated by Integration package Java");// V + Config.version);
        xmlw.writeStartElement("payment");
        
        xmlw = payment.getPaymentSpecificXml(xmlw);
        writeSimpleElement("customerrefno", order.getClientOrderNumber());
        writeSimpleElement("returnurl", payment.getReturnUrl());
        writeSimpleElement("cancelurl", payment.getCancelUrl());
        writeSimpleElement("currency", order.getCurrency());
        writeSimpleElement("amount", payment.getAmount().toString());
        writeSimpleElement("lang", payment.getPayPageLanguageCode());
        
        serializeCustomer(order, payment);
        
        if (payment.getVat() != null) {
            writeSimpleElement("vat", payment.getVat().toString());
        }
        
        if(order.getIsCompanyIdentity()) {
        	if(order.getCompanyCustomer().getIpAddress() != null) {
				writeSimpleElement("ipaddress", order.getCompanyCustomer().getIpAddress());
        	}
        } else {
        	if(order.getIndividualCustomer().getIpAddress() != null) {
				writeSimpleElement("ipaddress", order.getCompanyCustomer().getIpAddress());
        	}
        }
        
        serializeRows(rows);
        
        if (payment.getExcludedPaymentMethods() != null) {
            xmlw.writeStartElement("excludepaymentmethods");
            
            List<String> excludeList =  payment.getExcludedPaymentMethods();
            for (int i = 0; i < excludeList.size(); i++) {
        		writeSimpleElement("exclude", excludeList.get(i));
        	}
            
            xmlw.writeEndElement();
        }
        
        writeSimpleElement("iscompany", order.getIsCompanyIdentity() ? "true" : "false");
        writeSimpleElement("addinvoicefee", "false");
        xmlw.writeEndDocument();
        
        try {
            return new String(os.toByteArray(), "UTF-8");
        } catch (UnsupportedEncodingException e) {
        	throw new SveaWebPayException("Unsupported encoding UTF-8", e);
        }
    }
    
    private void serializeCustomer(CreateOrderBuilder order, HostedPayment<?> payment) {
    	try {
    		CustomerIdentity<?> customer;
    		if(order.getIsCompanyIdentity()) {
    			customer = order.getCompanyCustomer();
    		} else {
    			customer = order.getIndividualCustomer();
    		}
    		
			xmlw.writeStartElement("customer");
			
			//nordic country individual customer type
			if(customer.getNationalIdNumber()!=null) {
				writeSimpleElement("ssn", customer.getNationalIdNumber());
			}
			//euro country individual
			else if(!order.getIsCompanyIdentity()) {
				writeSimpleElement("ssn", ((IndividualCustomer)customer).getBirthDate().toString());
			}
			//euro country, Company customer and nationalId not set			
			else if(order.getIsCompanyIdentity()) {
				writeSimpleElement("ssn", ((CompanyCustomer)customer).getVatNumber());
			}
			
			//set for individual customer
			if(!order.getIsCompanyIdentity()) {
				IndividualCustomer individualCustomer = (IndividualCustomer)customer;
				
				if(individualCustomer.getFirstName() != null) {
					writeSimpleElement("firstname", individualCustomer.getFirstName());
				}
				
				if(individualCustomer.getLastName() != null) {
					writeSimpleElement("lastname", individualCustomer.getLastName());
				}
				
				if(individualCustomer.getInitials() != null) {
					writeSimpleElement("initials", individualCustomer.getInitials());
				}
				
				if(individualCustomer.getPhoneNumber() != null) {
					writeSimpleElement("phone", individualCustomer.getPhoneNumber().toString());
				}
				
				if(individualCustomer.getEmail() != null) {
					writeSimpleElement("email", individualCustomer.getEmail());
				}
				
				if(individualCustomer.getStreetAddress() != null) {
					writeSimpleElement("address", individualCustomer.getStreetAddress());
				}
				
				if(individualCustomer.getCoAddress() != null) {
					writeSimpleElement("address2", individualCustomer.getCoAddress());
				}
				
				if(individualCustomer.getHouseNumber() != null) {
					writeSimpleElement("housenumber", individualCustomer.getHouseNumber());
				}
				
				if(individualCustomer.getZipCode() != null) {
					writeSimpleElement("zip", individualCustomer.getZipCode());
				}
				
				if(individualCustomer.getLocality() != null) {
					writeSimpleElement("city", individualCustomer.getLocality().toString());
				}
			} else {
				CompanyCustomer companyCustomer = (CompanyCustomer)customer;
				
				if(companyCustomer.getCompanyName() != null) {
					writeSimpleElement("firstname", companyCustomer.getCompanyName());
				}
				
				if(companyCustomer.getPhoneNumber() != null) {
					writeSimpleElement("phone", companyCustomer.getPhoneNumber().toString());
				}
				
				if(companyCustomer.getEmail() != null) {
					writeSimpleElement("email", companyCustomer.getEmail());
				}
				
				if(companyCustomer.getStreetAddress() != null) {
					writeSimpleElement("address", companyCustomer.getStreetAddress());
				}
				
				if(companyCustomer.getCoAddress() != null) {
					writeSimpleElement("address2", companyCustomer.getCoAddress());
				}
				
				if(companyCustomer.getHouseNumber() != null) {
					writeSimpleElement("housenumber", companyCustomer.getHouseNumber());
				}
				
				if(companyCustomer.getZipCode() != null) {
					writeSimpleElement("zip", companyCustomer.getZipCode());
				}
				
				if(companyCustomer.getLocality() != null) {
					writeSimpleElement("city", companyCustomer.getLocality().toString());
				}
			}
			
			if(order.getCountryCode() != null) {
				writeSimpleElement("country", order.getCountryCode().toString());
			}
			
			xmlw.writeEndElement();
		} catch (XMLStreamException e) {
			e.printStackTrace();
		}
	}
    
	private void serializeRows(List<HostedOrderRowBuilder> rows) throws XMLStreamException {
        if (rows == null || rows.size() == 0) {
            return;
        }
        
        xmlw.writeStartElement("orderrows");
        
        for (HostedOrderRowBuilder row : rows) {
            serializeRow(row);
        }
        
        xmlw.writeEndElement();
    }
    
    private void serializeRow(HostedOrderRowBuilder row) throws XMLStreamException {
        xmlw.writeStartElement("row");
        
        writeSimpleElement("sku", row.getSku());
        writeSimpleElement("name", row.getName());
        writeSimpleElement("description", row.getDescription());
        
        if (row.getAmount() != null) {
            writeSimpleElement("amount", row.getAmount().toString());
        }
        
        if (row.getVat() != null) {
            writeSimpleElement("vat", row.getVat().toString());
        }
        
        if (row.getQuantity() != 0) {
            writeSimpleElement("quantity", Integer.toString(row.getQuantity()));
        }
        
        writeSimpleElement("unit", row.getUnit());
        
        xmlw.writeEndElement();
    }
}
