package se.sveaekonomi.webpay.integration.hosted.hostedadmin;

import static org.hamcrest.CoreMatchers.instanceOf;
import static org.junit.Assert.assertThat;

import java.util.Hashtable;

import junit.framework.TestCase;

import org.junit.Before;
import org.junit.Test;

import se.sveaekonomi.webpay.integration.config.ConfigurationProvider;
import se.sveaekonomi.webpay.integration.config.SveaConfig;
import se.sveaekonomi.webpay.integration.util.constant.COUNTRYCODE;
import se.sveaekonomi.webpay.integration.util.constant.PAYMENTTYPE;
import se.sveaekonomi.webpay.integration.util.security.Base64Util;
import se.sveaekonomi.webpay.integration.util.security.HashUtil;
import se.sveaekonomi.webpay.integration.util.security.HashUtil.HASHALGORITHM;

public class AnnulTransactionRequestTest extends TestCase {

	private ConfigurationProvider config;
	private AnnulTransactionRequest request;
	
	@Before
	public void setUp() {
		config = SveaConfig.getDefaultConfig();
		request = new AnnulTransactionRequest(config); 
		request.setCountryCode(COUNTRYCODE.SE);
	}
	
    @Test
    public void test_AnnulTransactionRequest_class_exists() {    	   	        
        assertThat( request, instanceOf(AnnulTransactionRequest.class) );
        assertThat( request, instanceOf(HostedAdminRequest.class) );
    }    
    
    @Test 
    public void test_getAnnulTransactionXml() {    	
    	this.request.setTransactionId( "123456" );    	
    	
    	String expectedXmlMessage = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><!--Message generated by Integration package Java--><annul><transactionid>123456</transactionid></annul>";
    	
    	assertEquals( request.getAnnulTransactionXml(), expectedXmlMessage );    
    }
    
    @Test
    public void test_prepareRequest() {
    	this.request.setTransactionId( "123456" );

		String merchantId = this.config.getMerchantId(PAYMENTTYPE.HOSTED, request.getCountryCode());
		String secretWord = this.config.getSecretWord(PAYMENTTYPE.HOSTED, request.getCountryCode());    	
    	
    	String expectedXmlMessage = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><!--Message generated by Integration package Java--><annul><transactionid>123456</transactionid></annul>";
    	String expectedXmlMessageBase64 = Base64Util.encodeBase64String(expectedXmlMessage);
    	String expectedMacSha512 =  HashUtil.createHash(expectedXmlMessageBase64 + secretWord, HASHALGORITHM.SHA_512);
    	
    	Hashtable<String, String> requestFields = this.request.prepareRequest();
    	assertEquals( requestFields.get("message"), expectedXmlMessageBase64 );
    	assertEquals( requestFields.get("mac"), expectedMacSha512 );
    	assertEquals( requestFields.get("merchantid"), merchantId );
    }
}
